/**
 * Matrice RBAC (source : docs/07-security-rbac/01-rbac.md §5, §8 ; docs/01-functional/
 * 04-acteurs-et-roles.md §2 ; ADR-008). Devient, une fois ce fichier livré, la source de
 * vérité courante de la matrice (docs/10-development-plan/05-audit-coherence.md, DT-07) :
 * une évolution de portée ou d'octroi se fait ici, pas dans une migration ni dans le
 * markdown source, qui reste la trace de la décision initiale (§9 de 01-rbac.md : « tests
 * générés depuis la matrice », pas l'inverse).
 *
 * Statuts (00-reference/00-conventions.md §2) :
 * - CONFIRMÉ : codes de permission, max_scope et limits par (rôle, permission), is_approval
 *   (préfixe `A·` de la matrice), les 11 rôles eux-mêmes — lecture directe de 01-rbac.md.
 * - DÉDUIT : `allowedScopeTypes` par rôle (jamais publié comme tableau littéral — déduit du
 *   type de périmètre des affectations données en exemple, 01-rbac.md §8) ; `supportedScopes`
 *   par permission (union des portées effectivement accordées à au moins un rôle dans la
 *   matrice — un minorant reproductible, pas une liste indépendamment publiée) ; les
 *   descriptions (libellés courts, la matrice ne documente que codes/portées/limits).
 * - À VALIDER : `isSensitive` — AV-092, `false` partout (aucune permission désignée par une
 *   source ; défaut du schéma). `RESP_PRODUCTION.finance.expense.approve.limits` — AV-058
 *   (montant non chiffré dans la matrice pour ce rôle précisément) : accordé sans `limits`.
 *   `attachments.attachment.manage` — AV-093 (permission générique, portée OWN pour les 11
 *   rôles : « Permission de l'opération » de SM-ATTACHMENT n'est pas résolvable avant qu'un
 *   module propriétaire, P2+, n'existe).
 *
 * Rôles proposés mais non créés (AV-004, OUVERT) : OPERATEUR_FERME, LIVREUR, CAISSIER —
 * volontairement absents de ROLES.
 */

export interface RoleSeed {
  readonly code: string;
  readonly name: string;
  readonly description: string;
  readonly allowedScopeTypes: readonly string[];
}

export interface PermissionSeed {
  readonly code: string;
  readonly module: string;
  readonly description: string;
  readonly supportedScopes: readonly string[];
  readonly isApproval: boolean;
  readonly isSensitive: boolean;
}

export interface RolePermissionSeed {
  readonly roleCode: string;
  readonly permissionCode: string;
  readonly maxScope: string;
  readonly limits?: Record<string, unknown>;
}

export interface RoleDiscountSetting {
  readonly key: string;
  readonly value: number;
  readonly ref: string;
}

// ---------------------------------------------------------------------------------------
// 11 rôles (docs/01-functional/04-acteurs-et-roles.md §2). Tous is_system=true (livrés
// avec le système, non supprimables), is_active=true.
// ---------------------------------------------------------------------------------------
export const ROLES: readonly RoleSeed[] = [
  {
    code: 'DIRECTION',
    name: 'Direction',
    description:
      'Pilotage global et contrôle : tour de contrôle, anomalies, validations au-dessus des seuils, activation des tarifs, notes de direction (CM §53).',
    allowedScopeTypes: ['GLOBAL'],
  },
  {
    code: 'ADMIN',
    name: 'Administrateur',
    description:
      'Configuration du système et gestion des droits : utilisateurs, rôles, appareils, sites, zones, emplacements, référentiels, paramètres, supervision de la synchronisation.',
    allowedScopeTypes: ['GLOBAL'],
  },
  {
    code: 'RESP_COMMERCIAL',
    name: 'Responsable commercial',
    description:
      "Pilotage de l'équipe commerciale (ventes, prospects, visites, présences, objectifs, clients inactifs, réaffectations, remises, dérogations de pointage) ; peut aussi être commercial opérationnel (CM §6).",
    allowedScopeTypes: ['TEAM'],
  },
  {
    code: 'COMMERCIAL_TERRAIN',
    name: 'Commercial terrain',
    description:
      'Prospection physique : prise de service, objectifs, prospects, visites, commandes, ventes depuis le stock mobile, encaissements, performances (CM §50).',
    allowedScopeTypes: ['ZONE'],
  },
  {
    code: 'COMMERCIAL_SEDENTAIRE',
    name: 'Commercial sédentaire',
    description:
      'Traitement des leads et clients sans déplacement permanent : clients issus de Kommo, commandes, suivi des livraisons et encaissements.',
    allowedScopeTypes: ['GLOBAL'],
  },
  {
    code: 'VENDEUR_PDV',
    name: 'Vendeur de point de vente',
    description:
      'Ventes et opérations du point de vente : caisse, ventes, encaissements, pertes, réceptions de transfert, réapprovisionnement, inventaire, clôture de caisse.',
    allowedScopeTypes: ['SITE'],
  },
  {
    code: 'RESP_PRODUCTION',
    name: 'Responsable production',
    description:
      "Pilotage des lots et de la production sur l'ensemble des fermes (AV-005) : effectifs, mortalités, consommations, œufs, incubations, validations de mortalité, coûts et performances (CM §34.5).",
    allowedScopeTypes: ['GLOBAL'],
  },
  {
    code: 'RESP_FERME',
    name: 'Responsable ferme',
    description:
      "Supervision opérationnelle d'une ferme : saisie du jour, collectes d'œufs, consommations, réceptions et stock, sorties vers commercialisation, validations locales sous seuil.",
    allowedScopeTypes: ['SITE'],
  },
  {
    code: 'MAGASINIER',
    name: 'Magasinier',
    description:
      'Réception, stockage, sorties et inventaires : alertes, réceptions, quantités acceptées, transferts, affectations de stock aux commerciaux, pertes, contrôles, inventaires (CM §51).',
    allowedScopeTypes: ['SITE'],
  },
  {
    code: 'RESP_ACHATS',
    name: 'Responsable achats',
    description:
      "Fournisseurs et approvisionnements : gestion des fournisseurs, instruction et validation des demandes d'achat, bons de commande, reliquats et rapprochements.",
    allowedScopeTypes: ['GLOBAL'],
  },
  {
    code: 'FINANCE',
    name: 'Comptabilité / Finance',
    description:
      'Encaissements, dépenses, créances, fournisseurs, reporting financier : suivi des créances et encaissements, sessions de caisse, dépenses, factures et paiements fournisseurs, coûts et marges (CM §34.6).',
    allowedScopeTypes: ['GLOBAL'],
  },
] as const;

// ---------------------------------------------------------------------------------------
// 117 permissions (docs/07-security-rbac/01-rbac.md §5). `module` = préfixe littéral du
// code (`org`, pas `organization` — les deux orthographes coexistent volontairement dans
// ce projet : `org.*` pour les codes de permission, `organization` pour les tables et le
// module de code, D01-ADM-core-administration.md §3).
// ---------------------------------------------------------------------------------------
export const PERMISSIONS: readonly PermissionSeed[] = [
  // identity (8)
  {
    code: 'identity.user.read',
    module: 'identity',
    description: 'Consulter les comptes utilisateurs',
    supportedScopes: ['ALL', 'TEAM', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'identity.user.manage',
    module: 'identity',
    description: 'Créer, modifier, suspendre, désactiver un compte utilisateur',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'identity.role.manage',
    module: 'identity',
    description: 'Créer et modifier les rôles et leurs permissions',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'identity.role_assignment.manage',
    module: 'identity',
    description: 'Affecter ou révoquer un rôle sur un périmètre',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'identity.device.read',
    module: 'identity',
    description: 'Consulter les appareils enrôlés',
    supportedScopes: ['ALL', 'TEAM', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  // is_approval=true : porté par 3 rôles avec le préfixe A· (RCO, RPR, RFE) ; la cellule
  // ADMIN de la matrice source est notée `ALL` sans A· — seule incohérence relevée dans
  // toute la matrice (RC-03 : « ADMIN ne détient aucune permission d'approbation métier »).
  // is_approval reste ici une propriété de la permission (colonne du schéma), pas de
  // l'octroi : traité comme une approbation administrative/sécurité, hors du champ « métier »
  // que RC-03 vise. Non résolu explicitement par une source — signalé, pas corrigé en silence.
  {
    code: 'identity.device.approve',
    module: 'identity',
    description: "Approuver l'enrôlement d'un appareil",
    supportedScopes: ['ALL', 'TEAM', 'SITE'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'identity.device.block',
    module: 'identity',
    description: 'Bloquer ou débloquer un appareil',
    supportedScopes: ['ALL', 'TEAM', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'identity.session.revoke',
    module: 'identity',
    description: "Révoquer une session ou un jeton d'authentification",
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },

  // org (3)
  {
    code: 'org.structure.read',
    module: 'org',
    description: 'Consulter sites, zones et emplacements',
    supportedScopes: ['ALL', 'ZONE', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'org.structure.manage',
    module: 'org',
    description: 'Créer et modifier sites, zones et emplacements',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'org.settings.manage',
    module: 'org',
    description: 'Modifier les paramètres système par défaut',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },

  // approvals (2)
  {
    code: 'approvals.request.read',
    module: 'approvals',
    description: 'Consulter les demandes de validation',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'approvals.policy.manage',
    module: 'approvals',
    description: 'Créer et modifier les politiques de contrôle',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },

  // attachments (1)
  {
    code: 'attachments.attachment.manage',
    module: 'attachments',
    description: 'Joindre une pièce justificative à une opération (AV-093)',
    supportedScopes: ['OWN'],
    isApproval: false,
    isSensitive: false,
  },

  // catalog (3)
  {
    code: 'catalog.product.read',
    module: 'catalog',
    description: 'Consulter le catalogue produits',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'catalog.product.manage',
    module: 'catalog',
    description: 'Créer et modifier des produits',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'catalog.reference.manage',
    module: 'catalog',
    description: 'Gérer les référentiels (unités, motifs, catégories)',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },

  // audit (1)
  {
    code: 'audit.log.read',
    module: 'audit',
    description: "Consulter le journal d'audit",
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },

  // sync (2)
  {
    code: 'sync.monitor.read',
    module: 'sync',
    description: "Consulter l'état de synchronisation des appareils",
    supportedScopes: ['ALL', 'TEAM', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sync.conflict.resolve',
    module: 'sync',
    description: 'Résoudre un conflit de synchronisation',
    supportedScopes: ['ALL', 'TEAM', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },

  // integrations (2)
  {
    code: 'integrations.kommo.manage',
    module: 'integrations',
    description: "Configurer l'intégration Kommo",
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'integrations.kommo.monitor',
    module: 'integrations',
    description: "Consulter l'état de l'intégration Kommo",
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },

  // comm (5)
  {
    code: 'comm.alert.read',
    module: 'comm',
    description: 'Consulter les alertes',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'comm.alert.manage',
    module: 'comm',
    description: 'Acquitter ou résoudre une alerte',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'comm.alert_rule.manage',
    module: 'comm',
    description: "Configurer les règles d'alerte",
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'comm.note.read',
    module: 'comm',
    description: 'Consulter les notes de direction',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'comm.note.publish',
    module: 'comm',
    description: 'Publier une note de direction',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },

  // crm (13)
  {
    code: 'crm.customer.read',
    module: 'crm',
    description: 'Consulter les comptes clients',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.customer.create',
    module: 'crm',
    description: 'Créer un compte client ou prospect',
    supportedScopes: ['TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.customer.update',
    module: 'crm',
    description: 'Modifier un compte client',
    supportedScopes: ['TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.customer.reassign',
    module: 'crm',
    description: 'Réaffecter un client à un autre titulaire',
    supportedScopes: ['ALL', 'TEAM'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.customer.mark_lost',
    module: 'crm',
    description: 'Marquer un client ou prospect comme perdu',
    supportedScopes: ['TEAM', 'OWN'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.customer.merge',
    module: 'crm',
    description: 'Fusionner deux comptes clients en doublon',
    supportedScopes: ['ALL', 'TEAM'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.customer.credit_manage',
    module: 'crm',
    description: "Gérer la limite de crédit d'un client",
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.visit.record',
    module: 'crm',
    description: 'Enregistrer une visite client',
    supportedScopes: ['OWN'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.visit.read',
    module: 'crm',
    description: 'Consulter les visites',
    supportedScopes: ['ALL', 'TEAM', 'OWN'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.interaction.record',
    module: 'crm',
    description: 'Enregistrer une interaction hors Kommo',
    supportedScopes: ['OWN'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.target.read',
    module: 'crm',
    description: 'Consulter les objectifs commerciaux',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.target.manage',
    module: 'crm',
    description: 'Définir les objectifs commerciaux',
    supportedScopes: ['ALL', 'TEAM'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'crm.pipeline.configure',
    module: 'crm',
    description: 'Configurer les étapes du pipeline commercial',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },

  // fieldwork (3)
  {
    code: 'fieldwork.checkin.perform',
    module: 'fieldwork',
    description: 'Effectuer une prise de service (pointage)',
    supportedScopes: ['OWN'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'fieldwork.session.read',
    module: 'fieldwork',
    description: 'Consulter les sessions de travail',
    supportedScopes: ['ALL', 'TEAM', 'OWN'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'fieldwork.checkin_override.approve',
    module: 'fieldwork',
    description: 'Approuver une dérogation de pointage hors zone',
    supportedScopes: ['ALL', 'TEAM'],
    isApproval: true,
    isSensitive: false,
  },

  // pricing (4)
  {
    code: 'pricing.price.read',
    module: 'pricing',
    description: 'Consulter les prix et règles tarifaires',
    supportedScopes: ['ALL', 'ZONE', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'pricing.rule.draft',
    module: 'pricing',
    description: 'Préparer une règle tarifaire',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'pricing.rule.activate',
    module: 'pricing',
    description: 'Activer une règle tarifaire',
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'pricing.campaign.manage',
    module: 'pricing',
    description: 'Gérer les campagnes commerciales',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },

  // sales (16)
  {
    code: 'sales.order.read',
    module: 'sales',
    description: 'Consulter les commandes clients',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.order.create',
    module: 'sales',
    description: 'Créer une commande client',
    supportedScopes: ['TEAM', 'OWN'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.order.cancel',
    module: 'sales',
    description: 'Annuler une commande client',
    supportedScopes: ['ALL', 'TEAM', 'OWN'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.order.fulfil',
    module: 'sales',
    description: 'Exécuter (livrer) une commande client',
    supportedScopes: ['TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.sale.read',
    module: 'sales',
    description: 'Consulter les ventes',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.sale.record',
    module: 'sales',
    description: 'Enregistrer une vente',
    supportedScopes: ['OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.sale.cancel',
    module: 'sales',
    description: 'Annuler une vente dans le délai direct',
    supportedScopes: ['OWN'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.sale_cancel.approve',
    module: 'sales',
    description: 'Approuver une annulation de vente hors délai direct',
    supportedScopes: ['ALL', 'TEAM', 'SITE'],
    isApproval: true,
    isSensitive: false,
  },
  // limits.max_discount_pct porté par l'octroi (role_permissions), pas ici (RC-06).
  {
    code: 'sales.price.override',
    module: 'sales',
    description: 'Appliquer une remise sur le prix de vente',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.price_override.approve',
    module: 'sales',
    description: 'Approuver une remise au-delà du plafond du vendeur',
    supportedScopes: ['ALL', 'TEAM'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'sales.credit_sale.record',
    module: 'sales',
    description: 'Enregistrer une vente à crédit',
    supportedScopes: ['TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.credit_limit_exceed.approve',
    module: 'sales',
    description: 'Approuver un dépassement de limite de crédit',
    supportedScopes: ['ALL', 'TEAM'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'sales.payment.record',
    module: 'sales',
    description: 'Enregistrer un encaissement client',
    supportedScopes: ['TEAM', 'OWN', 'SITE', 'ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.payment.read',
    module: 'sales',
    description: 'Consulter les encaissements clients',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'sales.payment.cancel',
    module: 'sales',
    description: 'Annuler un encaissement client',
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'sales.receivable.read',
    module: 'sales',
    description: 'Consulter les créances clients',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },

  // inventory (17)
  {
    code: 'inventory.stock.read',
    module: 'inventory',
    description: 'Consulter les soldes de stock',
    supportedScopes: ['ALL', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.valuation.read',
    module: 'inventory',
    description: 'Consulter la valorisation du stock (coûts, marges)',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.ledger.read',
    module: 'inventory',
    description: 'Consulter le registre des mouvements de stock',
    supportedScopes: ['ALL', 'ZONE', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.transfer.request',
    module: 'inventory',
    description: 'Demander un transfert de stock',
    supportedScopes: ['OWN', 'SITE', 'ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.transfer.dispatch',
    module: 'inventory',
    description: 'Expédier un transfert de stock',
    supportedScopes: ['OWN', 'SITE', 'ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.transfer.receive',
    module: 'inventory',
    description: 'Réceptionner un transfert de stock',
    supportedScopes: ['OWN', 'SITE', 'ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.transfer.cancel',
    module: 'inventory',
    description: 'Annuler un transfert de stock',
    supportedScopes: ['OWN', 'SITE', 'ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.transfer_discrepancy.approve',
    module: 'inventory',
    description: 'Approuver un écart de transfert (perte en transit)',
    supportedScopes: ['ALL', 'SITE'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'inventory.allocation.manage',
    module: 'inventory',
    description: 'Gérer les allocations et quotas de stock',
    supportedScopes: ['ALL', 'ZONE', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.loss.declare',
    module: 'inventory',
    description: 'Déclarer une perte de stock',
    supportedScopes: ['OWN', 'SITE', 'ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.loss.approve',
    module: 'inventory',
    description: 'Approuver une déclaration de perte',
    supportedScopes: ['ALL', 'ZONE', 'SITE'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'inventory.count.perform',
    module: 'inventory',
    description: 'Réaliser un inventaire',
    supportedScopes: ['OWN', 'SITE', 'ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.count.approve',
    module: 'inventory',
    description: "Approuver l'écart d'un inventaire",
    supportedScopes: ['ALL', 'ZONE', 'SITE'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'inventory.consumption.record',
    module: 'inventory',
    description: "Enregistrer une consommation d'intrants",
    supportedScopes: ['SITE', 'ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.threshold.manage',
    module: 'inventory',
    description: 'Définir les seuils de réapprovisionnement',
    supportedScopes: ['ALL', 'ZONE', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.opening.post',
    module: 'inventory',
    description: 'Poster un stock initial (ouverture)',
    supportedScopes: ['ALL', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'inventory.cost_entry.record',
    module: 'inventory',
    description: 'Enregistrer une écriture de coût',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },

  // production (5)
  {
    code: 'production.lot.read',
    module: 'production',
    description: 'Consulter les lots de production',
    supportedScopes: ['ALL', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'production.lot.manage',
    module: 'production',
    description: 'Créer et clôturer un lot de production',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'production.daily.record',
    module: 'production',
    description: 'Enregistrer la saisie du jour (effectifs, pesées, observations)',
    supportedScopes: ['ALL', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'production.mortality.approve',
    module: 'production',
    description: 'Approuver une mortalité au-dessus du seuil',
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'production.incubation.record',
    module: 'production',
    description: "Enregistrer une étape d'incubation",
    supportedScopes: ['ALL', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },

  // procurement (10)
  {
    code: 'procurement.supplier.read',
    module: 'procurement',
    description: 'Consulter les fournisseurs',
    supportedScopes: ['ALL', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'procurement.supplier.manage',
    module: 'procurement',
    description: 'Créer et modifier un fournisseur',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'procurement.request.create',
    module: 'procurement',
    description: "Créer une demande d'achat",
    supportedScopes: ['ALL', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'procurement.request.approve',
    module: 'procurement',
    description: "Approuver une demande d'achat",
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'procurement.order.read',
    module: 'procurement',
    description: 'Consulter les bons de commande',
    supportedScopes: ['ALL', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'procurement.order.manage',
    module: 'procurement',
    description: 'Émettre et modifier un bon de commande',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'procurement.order.approve',
    module: 'procurement',
    description: 'Approuver un bon de commande',
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'procurement.receipt.record',
    module: 'procurement',
    description: 'Enregistrer une réception de marchandises',
    supportedScopes: ['ALL', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'procurement.receipt.cancel',
    module: 'procurement',
    description: 'Annuler une réception de marchandises',
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'procurement.receipt_exception.approve',
    module: 'procurement',
    description: 'Approuver une exception de réception (écart, sans bon de commande)',
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },

  // finance (14)
  {
    code: 'finance.cash.read',
    module: 'finance',
    description: 'Consulter les comptes de trésorerie',
    supportedScopes: ['ALL', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'finance.cash_account.manage',
    module: 'finance',
    description: 'Créer et modifier un compte de trésorerie',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'finance.cash_session.operate',
    module: 'finance',
    description: 'Ouvrir et clôturer une session de caisse',
    supportedScopes: ['SITE', 'ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'finance.cash_session.validate',
    module: 'finance',
    description: 'Valider une session de caisse avec écart',
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'finance.cash_transfer.record',
    module: 'finance',
    description: 'Enregistrer une remise de fonds entre comptes',
    supportedScopes: ['OWN', 'SITE', 'ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'finance.expense.read',
    module: 'finance',
    description: 'Consulter les dépenses',
    supportedScopes: ['ALL', 'TEAM', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'finance.expense.record',
    module: 'finance',
    description: 'Enregistrer une dépense',
    supportedScopes: ['ALL', 'OWN', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'finance.expense.approve',
    module: 'finance',
    description: 'Approuver une dépense',
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'finance.expense.pay',
    module: 'finance',
    description: 'Payer une dépense approuvée',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'finance.payable.read',
    module: 'finance',
    description: 'Consulter les dettes fournisseurs',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'finance.supplier_invoice.record',
    module: 'finance',
    description: 'Enregistrer une facture fournisseur',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'finance.supplier_invoice.approve',
    module: 'finance',
    description: 'Approuver une facture fournisseur (écart)',
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },
  {
    code: 'finance.supplier_payment.record',
    module: 'finance',
    description: 'Enregistrer un paiement fournisseur',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'finance.supplier_payment.approve',
    module: 'finance',
    description: 'Approuver un paiement fournisseur',
    supportedScopes: ['ALL'],
    isApproval: true,
    isSensitive: false,
  },

  // analytics (9)
  {
    code: 'analytics.dashboard.direction',
    module: 'analytics',
    description: 'Consulter le tableau de bord Direction (tour de contrôle)',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'analytics.dashboard.commercial',
    module: 'analytics',
    description: 'Consulter le tableau de bord commercial',
    supportedScopes: ['ALL', 'TEAM', 'OWN'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'analytics.dashboard.distribution',
    module: 'analytics',
    description: 'Consulter le tableau de bord distribution / points de vente',
    supportedScopes: ['ALL', 'ZONE', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'analytics.dashboard.stock',
    module: 'analytics',
    description: 'Consulter le tableau de bord stock',
    supportedScopes: ['ALL', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'analytics.dashboard.production',
    module: 'analytics',
    description: 'Consulter le tableau de bord production',
    supportedScopes: ['ALL', 'SITE'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'analytics.dashboard.finance',
    module: 'analytics',
    description: 'Consulter le tableau de bord finance',
    supportedScopes: ['ALL'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'analytics.explore',
    module: 'analytics',
    description: "Utiliser l'explorateur de données (tableaux libres)",
    supportedScopes: ['ALL', 'TEAM'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'analytics.view.share',
    module: 'analytics',
    description: "Partager une vue sauvegardée de l'explorateur",
    supportedScopes: ['ALL', 'TEAM'],
    isApproval: false,
    isSensitive: false,
  },
  {
    code: 'analytics.export',
    module: 'analytics',
    description: 'Exporter des données (CSV, XLSX)',
    supportedScopes: ['ALL', 'TEAM'],
    isApproval: false,
    isSensitive: false,
  },
] as const;

function grants(
  roleCode: string,
  entries: ReadonlyArray<readonly [string, string, Record<string, unknown>?]>,
): RolePermissionSeed[] {
  return entries.map(([permissionCode, maxScope, limits]) =>
    limits
      ? { roleCode, permissionCode, maxScope, limits }
      : { roleCode, permissionCode, maxScope },
  );
}

// ---------------------------------------------------------------------------------------
// Matrice d'octroi (472 lignes, docs/07-security-rbac/01-rbac.md §5, transposée par rôle).
// `sales.price.override` porte le seul `limits` chiffré par la matrice (RC-06, AV-026) ;
// VENDEUR_PDV n'a volontairement aucune ligne pour cette permission (annotée « 0 % » dans
// la matrice source plutôt que silencieusement omise).
// ---------------------------------------------------------------------------------------
export const ROLE_PERMISSIONS: readonly RolePermissionSeed[] = [
  // DIRECTION — 77, toujours ALL
  ...grants('DIRECTION', [
    ['identity.user.read', 'ALL'],
    ['identity.device.read', 'ALL'],
    ['identity.device.block', 'ALL'],
    ['identity.session.revoke', 'ALL'],
    ['org.structure.read', 'ALL'],
    ['org.settings.manage', 'ALL'],
    ['approvals.request.read', 'ALL'],
    ['approvals.policy.manage', 'ALL'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['audit.log.read', 'ALL'],
    ['sync.monitor.read', 'ALL'],
    ['sync.conflict.resolve', 'ALL'],
    ['integrations.kommo.monitor', 'ALL'],
    ['comm.alert.read', 'ALL'],
    ['comm.alert.manage', 'ALL'],
    ['comm.alert_rule.manage', 'ALL'],
    ['comm.note.read', 'ALL'],
    ['comm.note.publish', 'ALL'],
    ['crm.customer.read', 'ALL'],
    ['crm.customer.reassign', 'ALL'],
    ['crm.customer.merge', 'ALL'],
    ['crm.customer.credit_manage', 'ALL'],
    ['crm.visit.read', 'ALL'],
    ['crm.target.read', 'ALL'],
    ['crm.target.manage', 'ALL'],
    ['crm.pipeline.configure', 'ALL'],
    ['fieldwork.session.read', 'ALL'],
    ['fieldwork.checkin_override.approve', 'ALL'],
    ['pricing.price.read', 'ALL'],
    ['pricing.rule.draft', 'ALL'],
    ['pricing.rule.activate', 'ALL'],
    ['pricing.campaign.manage', 'ALL'],
    ['sales.order.read', 'ALL'],
    ['sales.order.cancel', 'ALL'],
    ['sales.sale.read', 'ALL'],
    ['sales.sale_cancel.approve', 'ALL'],
    ['sales.price.override', 'ALL'],
    ['sales.price_override.approve', 'ALL'],
    ['sales.credit_limit_exceed.approve', 'ALL'],
    ['sales.payment.read', 'ALL'],
    ['sales.payment.cancel', 'ALL'],
    ['sales.receivable.read', 'ALL'],
    ['inventory.stock.read', 'ALL'],
    ['inventory.valuation.read', 'ALL'],
    ['inventory.ledger.read', 'ALL'],
    ['inventory.transfer_discrepancy.approve', 'ALL'],
    ['inventory.allocation.manage', 'ALL'],
    ['inventory.loss.approve', 'ALL'],
    ['inventory.count.approve', 'ALL'],
    ['inventory.threshold.manage', 'ALL'],
    ['production.lot.read', 'ALL'],
    ['production.mortality.approve', 'ALL'],
    ['procurement.supplier.read', 'ALL'],
    ['procurement.request.create', 'ALL'],
    ['procurement.request.approve', 'ALL'],
    ['procurement.order.read', 'ALL'],
    ['procurement.order.approve', 'ALL'],
    ['procurement.receipt.cancel', 'ALL'],
    ['procurement.receipt_exception.approve', 'ALL'],
    ['finance.cash.read', 'ALL'],
    ['finance.cash_session.validate', 'ALL'],
    ['finance.expense.read', 'ALL'],
    ['finance.expense.record', 'ALL'],
    ['finance.expense.approve', 'ALL'],
    ['finance.payable.read', 'ALL'],
    ['finance.supplier_invoice.approve', 'ALL'],
    ['finance.supplier_payment.approve', 'ALL'],
    ['analytics.dashboard.direction', 'ALL'],
    ['analytics.dashboard.commercial', 'ALL'],
    ['analytics.dashboard.distribution', 'ALL'],
    ['analytics.dashboard.stock', 'ALL'],
    ['analytics.dashboard.production', 'ALL'],
    ['analytics.dashboard.finance', 'ALL'],
    ['analytics.explore', 'ALL'],
    ['analytics.view.share', 'ALL'],
    ['analytics.export', 'ALL'],
  ]),

  // ADMIN — 28, toujours ALL (identity.device.approve inclus, voir commentaire PERMISSIONS)
  ...grants('ADMIN', [
    ['identity.user.read', 'ALL'],
    ['identity.user.manage', 'ALL'],
    ['identity.role.manage', 'ALL'],
    ['identity.role_assignment.manage', 'ALL'],
    ['identity.device.read', 'ALL'],
    ['identity.device.approve', 'ALL'],
    ['identity.device.block', 'ALL'],
    ['identity.session.revoke', 'ALL'],
    ['org.structure.read', 'ALL'],
    ['org.structure.manage', 'ALL'],
    ['org.settings.manage', 'ALL'],
    ['approvals.policy.manage', 'ALL'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['catalog.product.manage', 'ALL'],
    ['catalog.reference.manage', 'ALL'],
    ['audit.log.read', 'ALL'],
    ['sync.monitor.read', 'ALL'],
    ['sync.conflict.resolve', 'ALL'],
    ['integrations.kommo.manage', 'ALL'],
    ['integrations.kommo.monitor', 'ALL'],
    ['comm.alert.read', 'ALL'],
    ['comm.alert.manage', 'ALL'],
    ['comm.alert_rule.manage', 'ALL'],
    ['comm.note.read', 'ALL'],
    ['crm.customer.merge', 'ALL'],
    ['crm.pipeline.configure', 'ALL'],
    ['inventory.opening.post', 'ALL'],
  ]),

  // RESP_COMMERCIAL — 58
  ...grants('RESP_COMMERCIAL', [
    ['identity.user.read', 'TEAM'],
    ['identity.device.read', 'TEAM'],
    ['identity.device.approve', 'TEAM'],
    ['identity.device.block', 'TEAM'],
    ['org.structure.read', 'ALL'],
    ['approvals.request.read', 'TEAM'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['sync.monitor.read', 'TEAM'],
    ['sync.conflict.resolve', 'TEAM'],
    ['integrations.kommo.monitor', 'ALL'],
    ['comm.alert.read', 'TEAM'],
    ['comm.alert.manage', 'TEAM'],
    ['comm.note.read', 'ALL'],
    ['crm.customer.read', 'TEAM'],
    ['crm.customer.create', 'TEAM'],
    ['crm.customer.update', 'TEAM'],
    ['crm.customer.reassign', 'TEAM'],
    ['crm.customer.mark_lost', 'TEAM'],
    ['crm.customer.merge', 'TEAM'],
    ['crm.visit.record', 'OWN'],
    ['crm.visit.read', 'TEAM'],
    ['crm.interaction.record', 'OWN'],
    ['crm.target.read', 'TEAM'],
    ['crm.target.manage', 'TEAM'],
    ['fieldwork.checkin.perform', 'OWN'],
    ['fieldwork.session.read', 'TEAM'],
    ['fieldwork.checkin_override.approve', 'TEAM'],
    ['pricing.price.read', 'ALL'],
    ['pricing.rule.draft', 'ALL'],
    ['pricing.campaign.manage', 'ALL'],
    ['sales.order.read', 'TEAM'],
    ['sales.order.create', 'TEAM'],
    ['sales.order.cancel', 'TEAM'],
    ['sales.order.fulfil', 'TEAM'],
    ['sales.sale.read', 'TEAM'],
    ['sales.sale.record', 'OWN'],
    ['sales.sale.cancel', 'OWN'],
    ['sales.sale_cancel.approve', 'TEAM'],
    ['sales.price.override', 'TEAM', { max_discount_pct: 15 }],
    ['sales.price_override.approve', 'TEAM'],
    ['sales.credit_sale.record', 'TEAM'],
    ['sales.credit_limit_exceed.approve', 'TEAM'],
    ['sales.payment.record', 'TEAM'],
    ['sales.payment.read', 'TEAM'],
    ['sales.receivable.read', 'TEAM'],
    ['inventory.stock.read', 'ALL'],
    ['inventory.ledger.read', 'ZONE'],
    ['inventory.allocation.manage', 'ZONE'],
    ['inventory.loss.approve', 'ZONE'],
    ['inventory.count.approve', 'ZONE'],
    ['inventory.threshold.manage', 'ZONE'],
    ['finance.expense.read', 'TEAM'],
    ['analytics.dashboard.commercial', 'TEAM'],
    ['analytics.dashboard.distribution', 'ZONE'],
    ['analytics.explore', 'TEAM'],
    ['analytics.view.share', 'TEAM'],
    ['analytics.export', 'TEAM'],
  ]),

  // COMMERCIAL_TERRAIN — 43
  ...grants('COMMERCIAL_TERRAIN', [
    ['org.structure.read', 'ZONE'],
    ['approvals.request.read', 'OWN'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['comm.alert.read', 'OWN'],
    ['comm.alert.manage', 'OWN'],
    ['comm.note.read', 'ALL'],
    ['crm.customer.read', 'OWN'],
    ['crm.customer.create', 'OWN'],
    ['crm.customer.update', 'OWN'],
    ['crm.customer.mark_lost', 'OWN'],
    ['crm.visit.record', 'OWN'],
    ['crm.visit.read', 'OWN'],
    ['crm.interaction.record', 'OWN'],
    ['crm.target.read', 'OWN'],
    ['fieldwork.checkin.perform', 'OWN'],
    ['fieldwork.session.read', 'OWN'],
    ['pricing.price.read', 'ZONE'],
    ['sales.order.read', 'OWN'],
    ['sales.order.create', 'OWN'],
    ['sales.order.cancel', 'OWN'],
    ['sales.order.fulfil', 'OWN'],
    ['sales.sale.read', 'OWN'],
    ['sales.sale.record', 'OWN'],
    ['sales.sale.cancel', 'OWN'],
    ['sales.price.override', 'OWN', { max_discount_pct: 5 }],
    ['sales.credit_sale.record', 'OWN'],
    ['sales.payment.record', 'OWN'],
    ['sales.payment.read', 'OWN'],
    ['sales.receivable.read', 'OWN'],
    ['inventory.stock.read', 'OWN'],
    ['inventory.ledger.read', 'OWN'],
    ['inventory.transfer.request', 'OWN'],
    ['inventory.transfer.dispatch', 'OWN'],
    ['inventory.transfer.receive', 'OWN'],
    ['inventory.transfer.cancel', 'OWN'],
    ['inventory.loss.declare', 'OWN'],
    ['inventory.count.perform', 'OWN'],
    ['finance.cash.read', 'OWN'],
    ['finance.cash_transfer.record', 'OWN'],
    ['finance.expense.read', 'OWN'],
    ['finance.expense.record', 'OWN'],
    ['analytics.dashboard.commercial', 'OWN'],
  ]),

  // COMMERCIAL_SEDENTAIRE — 33
  ...grants('COMMERCIAL_SEDENTAIRE', [
    ['org.structure.read', 'ALL'],
    ['approvals.request.read', 'OWN'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['comm.alert.read', 'OWN'],
    ['comm.alert.manage', 'OWN'],
    ['comm.note.read', 'ALL'],
    ['crm.customer.read', 'OWN'],
    ['crm.customer.create', 'OWN'],
    ['crm.customer.update', 'OWN'],
    ['crm.customer.mark_lost', 'OWN'],
    ['crm.visit.read', 'OWN'],
    ['crm.interaction.record', 'OWN'],
    ['crm.target.read', 'OWN'],
    ['pricing.price.read', 'ALL'],
    ['sales.order.read', 'OWN'],
    ['sales.order.create', 'OWN'],
    ['sales.order.cancel', 'OWN'],
    ['sales.order.fulfil', 'OWN'],
    ['sales.sale.read', 'OWN'],
    ['sales.sale.record', 'OWN'],
    ['sales.sale.cancel', 'OWN'],
    ['sales.price.override', 'OWN', { max_discount_pct: 5 }],
    ['sales.credit_sale.record', 'OWN'],
    ['sales.payment.record', 'OWN'],
    ['sales.payment.read', 'OWN'],
    ['sales.receivable.read', 'OWN'],
    ['inventory.stock.read', 'ALL'],
    ['finance.cash.read', 'OWN'],
    ['finance.cash_transfer.record', 'OWN'],
    ['finance.expense.read', 'OWN'],
    ['finance.expense.record', 'OWN'],
    ['analytics.dashboard.commercial', 'OWN'],
  ]),

  // VENDEUR_PDV — 36 (sales.price.override délibérément absent : plafond 0 %, AV-026)
  ...grants('VENDEUR_PDV', [
    ['org.structure.read', 'SITE'],
    ['approvals.request.read', 'OWN'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['comm.alert.read', 'SITE'],
    ['comm.alert.manage', 'SITE'],
    ['comm.note.read', 'ALL'],
    ['crm.customer.read', 'SITE'],
    ['crm.customer.create', 'SITE'],
    ['crm.customer.update', 'SITE'],
    ['crm.target.read', 'SITE'],
    ['pricing.price.read', 'SITE'],
    ['sales.order.read', 'SITE'],
    ['sales.order.fulfil', 'SITE'],
    ['sales.sale.read', 'SITE'],
    ['sales.sale.record', 'SITE'],
    ['sales.sale.cancel', 'OWN'],
    ['sales.credit_sale.record', 'SITE'],
    ['sales.payment.record', 'SITE'],
    ['sales.payment.read', 'SITE'],
    ['sales.receivable.read', 'SITE'],
    ['inventory.stock.read', 'SITE'],
    ['inventory.ledger.read', 'SITE'],
    ['inventory.transfer.request', 'SITE'],
    ['inventory.transfer.dispatch', 'SITE'],
    ['inventory.transfer.receive', 'SITE'],
    ['inventory.transfer.cancel', 'SITE'],
    ['inventory.loss.declare', 'SITE'],
    ['inventory.count.perform', 'SITE'],
    ['inventory.consumption.record', 'SITE'],
    ['finance.cash.read', 'SITE'],
    ['finance.cash_session.operate', 'SITE'],
    ['finance.cash_transfer.record', 'SITE'],
    ['finance.expense.read', 'SITE'],
    ['finance.expense.record', 'SITE'],
    ['analytics.dashboard.distribution', 'SITE'],
  ]),

  // RESP_PRODUCTION — 43
  ...grants('RESP_PRODUCTION', [
    ['identity.user.read', 'SITE'],
    ['identity.device.approve', 'SITE'],
    ['identity.device.block', 'SITE'],
    ['org.structure.read', 'ALL'],
    ['approvals.request.read', 'ALL'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['sync.monitor.read', 'SITE'],
    ['sync.conflict.resolve', 'ALL'],
    ['comm.alert.read', 'ALL'],
    ['comm.alert.manage', 'ALL'],
    ['comm.note.read', 'ALL'],
    ['inventory.stock.read', 'ALL'],
    ['inventory.valuation.read', 'ALL'],
    ['inventory.ledger.read', 'ALL'],
    ['inventory.transfer.request', 'ALL'],
    ['inventory.transfer.dispatch', 'ALL'],
    ['inventory.transfer.receive', 'ALL'],
    ['inventory.transfer.cancel', 'ALL'],
    ['inventory.transfer_discrepancy.approve', 'ALL'],
    ['inventory.loss.declare', 'ALL'],
    ['inventory.loss.approve', 'ALL'],
    ['inventory.count.perform', 'ALL'],
    ['inventory.count.approve', 'ALL'],
    ['inventory.consumption.record', 'ALL'],
    ['inventory.threshold.manage', 'ALL'],
    ['production.lot.read', 'ALL'],
    ['production.lot.manage', 'ALL'],
    ['production.daily.record', 'ALL'],
    ['production.mortality.approve', 'ALL'],
    ['production.incubation.record', 'ALL'],
    ['procurement.supplier.read', 'ALL'],
    ['procurement.request.create', 'ALL'],
    ['procurement.order.read', 'ALL'],
    ['procurement.receipt.record', 'ALL'],
    // limits non chiffré par la source pour ce rôle précisément (AV-058, voir en-tête).
    ['finance.expense.read', 'ALL'],
    ['finance.expense.record', 'ALL'],
    ['finance.expense.approve', 'ALL'],
    ['analytics.dashboard.stock', 'ALL'],
    ['analytics.dashboard.production', 'ALL'],
    ['analytics.explore', 'ALL'],
    ['analytics.view.share', 'ALL'],
    ['analytics.export', 'ALL'],
  ]),

  // RESP_FERME — 52
  ...grants('RESP_FERME', [
    ['identity.user.read', 'SITE'],
    ['identity.device.read', 'SITE'],
    ['identity.device.approve', 'SITE'],
    ['identity.device.block', 'SITE'],
    ['org.structure.read', 'SITE'],
    ['approvals.request.read', 'SITE'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['sync.monitor.read', 'SITE'],
    ['sync.conflict.resolve', 'SITE'],
    ['comm.alert.read', 'SITE'],
    ['comm.alert.manage', 'SITE'],
    ['comm.note.read', 'ALL'],
    ['crm.customer.read', 'SITE'],
    ['crm.customer.create', 'SITE'],
    ['pricing.price.read', 'SITE'],
    ['sales.sale.read', 'SITE'],
    ['sales.sale.record', 'SITE'],
    ['sales.sale.cancel', 'OWN'],
    ['sales.sale_cancel.approve', 'SITE'],
    ['sales.price.override', 'SITE', { max_discount_pct: 5 }],
    ['sales.credit_sale.record', 'SITE'],
    ['sales.payment.record', 'SITE'],
    ['sales.payment.read', 'SITE'],
    ['sales.receivable.read', 'SITE'],
    ['inventory.stock.read', 'SITE'],
    ['inventory.ledger.read', 'SITE'],
    ['inventory.transfer.request', 'SITE'],
    ['inventory.transfer.dispatch', 'SITE'],
    ['inventory.transfer.receive', 'SITE'],
    ['inventory.transfer.cancel', 'SITE'],
    ['inventory.transfer_discrepancy.approve', 'SITE'],
    ['inventory.allocation.manage', 'SITE'],
    ['inventory.loss.declare', 'SITE'],
    ['inventory.loss.approve', 'SITE'],
    ['inventory.count.perform', 'SITE'],
    ['inventory.count.approve', 'SITE'],
    ['inventory.consumption.record', 'SITE'],
    ['inventory.threshold.manage', 'SITE'],
    ['production.lot.read', 'SITE'],
    ['production.daily.record', 'SITE'],
    ['production.incubation.record', 'SITE'],
    ['procurement.supplier.read', 'SITE'],
    ['procurement.request.create', 'SITE'],
    ['procurement.order.read', 'SITE'],
    ['procurement.receipt.record', 'SITE'],
    ['finance.cash.read', 'OWN'],
    ['finance.cash_transfer.record', 'OWN'],
    ['finance.expense.read', 'SITE'],
    ['finance.expense.record', 'SITE'],
    ['analytics.dashboard.stock', 'SITE'],
    ['analytics.dashboard.production', 'SITE'],
  ]),

  // MAGASINIER — 34
  ...grants('MAGASINIER', [
    ['identity.user.read', 'SITE'],
    ['identity.device.read', 'SITE'],
    ['org.structure.read', 'SITE'],
    ['approvals.request.read', 'OWN'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['sync.monitor.read', 'SITE'],
    ['sync.conflict.resolve', 'SITE'],
    ['comm.alert.read', 'SITE'],
    ['comm.alert.manage', 'SITE'],
    ['comm.note.read', 'ALL'],
    ['sales.order.read', 'SITE'],
    ['sales.order.fulfil', 'SITE'],
    ['inventory.stock.read', 'SITE'],
    ['inventory.ledger.read', 'SITE'],
    ['inventory.transfer.request', 'SITE'],
    ['inventory.transfer.dispatch', 'SITE'],
    ['inventory.transfer.receive', 'SITE'],
    ['inventory.transfer.cancel', 'SITE'],
    ['inventory.transfer_discrepancy.approve', 'SITE'],
    ['inventory.allocation.manage', 'SITE'],
    ['inventory.loss.declare', 'SITE'],
    ['inventory.count.perform', 'SITE'],
    ['inventory.consumption.record', 'SITE'],
    ['inventory.threshold.manage', 'SITE'],
    ['inventory.opening.post', 'SITE'],
    ['procurement.supplier.read', 'ALL'],
    ['procurement.request.create', 'SITE'],
    ['procurement.order.read', 'SITE'],
    ['procurement.receipt.record', 'SITE'],
    ['finance.expense.read', 'OWN'],
    ['finance.expense.record', 'OWN'],
    ['analytics.dashboard.distribution', 'SITE'],
    ['analytics.dashboard.stock', 'SITE'],
  ]),

  // RESP_ACHATS — 26
  ...grants('RESP_ACHATS', [
    ['org.structure.read', 'ALL'],
    ['approvals.request.read', 'ALL'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['sync.conflict.resolve', 'ALL'],
    ['comm.alert.read', 'ALL'],
    ['comm.alert.manage', 'ALL'],
    ['comm.note.read', 'ALL'],
    ['inventory.stock.read', 'ALL'],
    ['inventory.valuation.read', 'ALL'],
    ['production.lot.read', 'ALL'],
    ['procurement.supplier.read', 'ALL'],
    ['procurement.supplier.manage', 'ALL'],
    ['procurement.request.create', 'ALL'],
    ['procurement.request.approve', 'ALL'],
    ['procurement.order.read', 'ALL'],
    ['procurement.order.manage', 'ALL'],
    ['procurement.receipt.cancel', 'ALL'],
    ['procurement.receipt_exception.approve', 'ALL'],
    ['finance.expense.read', 'ALL'],
    ['finance.expense.record', 'ALL'],
    ['finance.payable.read', 'ALL'],
    ['analytics.dashboard.stock', 'ALL'],
    ['analytics.explore', 'ALL'],
    ['analytics.view.share', 'ALL'],
    ['analytics.export', 'ALL'],
  ]),

  // FINANCE — 53
  ...grants('FINANCE', [
    ['identity.user.read', 'ALL'],
    ['org.structure.read', 'ALL'],
    ['approvals.request.read', 'ALL'],
    ['attachments.attachment.manage', 'OWN'],
    ['catalog.product.read', 'ALL'],
    ['audit.log.read', 'ALL'],
    ['sync.conflict.resolve', 'ALL'],
    ['comm.alert.read', 'ALL'],
    ['comm.alert.manage', 'ALL'],
    ['comm.note.read', 'ALL'],
    ['crm.customer.read', 'ALL'],
    ['crm.customer.credit_manage', 'ALL'],
    ['pricing.price.read', 'ALL'],
    ['sales.order.read', 'ALL'],
    ['sales.sale.read', 'ALL'],
    ['sales.sale_cancel.approve', 'ALL'],
    ['sales.credit_limit_exceed.approve', 'ALL'],
    ['sales.payment.record', 'ALL'],
    ['sales.payment.read', 'ALL'],
    ['sales.payment.cancel', 'ALL'],
    ['sales.receivable.read', 'ALL'],
    ['inventory.stock.read', 'ALL'],
    ['inventory.valuation.read', 'ALL'],
    ['inventory.ledger.read', 'ALL'],
    ['inventory.count.perform', 'ALL'],
    ['inventory.count.approve', 'ALL'],
    ['inventory.opening.post', 'ALL'],
    ['inventory.cost_entry.record', 'ALL'],
    ['production.lot.read', 'ALL'],
    ['procurement.supplier.read', 'ALL'],
    ['procurement.request.create', 'ALL'],
    ['procurement.order.read', 'ALL'],
    ['finance.cash.read', 'ALL'],
    ['finance.cash_account.manage', 'ALL'],
    ['finance.cash_session.operate', 'ALL'],
    ['finance.cash_session.validate', 'ALL'],
    ['finance.cash_transfer.record', 'ALL'],
    ['finance.expense.read', 'ALL'],
    ['finance.expense.record', 'ALL'],
    ['finance.expense.approve', 'ALL'],
    ['finance.expense.pay', 'ALL'],
    ['finance.payable.read', 'ALL'],
    ['finance.supplier_invoice.record', 'ALL'],
    ['finance.supplier_invoice.approve', 'ALL'],
    ['finance.supplier_payment.record', 'ALL'],
    ['analytics.dashboard.commercial', 'ALL'],
    ['analytics.dashboard.distribution', 'ALL'],
    ['analytics.dashboard.stock', 'ALL'],
    ['analytics.dashboard.production', 'ALL'],
    ['analytics.dashboard.finance', 'ALL'],
    ['analytics.explore', 'ALL'],
    ['analytics.view.share', 'ALL'],
    ['analytics.export', 'ALL'],
  ]),
];

// ---------------------------------------------------------------------------------------
// pricing.max_discount_pct.<ROLE> (organization.system_settings, AV-026) : dérivé des
// mêmes limits que sales.price.override ci-dessus, une clé par rôle qui porte une remise
// (VENDEUR_PDV = 0 %, sans ligne role_permissions ni clé ici : le plafond vient de
// l'absence d'octroi, pas d'une valeur nulle stockée).
// ---------------------------------------------------------------------------------------
export const ROLE_DISCOUNT_SETTINGS: readonly RoleDiscountSetting[] = [
  { key: 'pricing.max_discount_pct.RESP_COMMERCIAL', value: 15, ref: 'AV-026' },
  { key: 'pricing.max_discount_pct.COMMERCIAL_TERRAIN', value: 5, ref: 'AV-026' },
  { key: 'pricing.max_discount_pct.COMMERCIAL_SEDENTAIRE', value: 5, ref: 'AV-026' },
  { key: 'pricing.max_discount_pct.RESP_FERME', value: 5, ref: 'AV-026' },
] as const;
