/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface ApprovalsApprovalRequests {
  active_pending_key: string | null;
  amount_xaf: number | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  decided_at: Date | null;
  decided_by: Buffer | null;
  decision_comment: string | null;
  decision_option: string | null;
  escalated_at: Date | null;
  id: Buffer;
  operation_type: string;
  policy_id: Buffer | null;
  policy_version: number | null;
  requested_at: Date;
  requested_by: Buffer;
  required_attachment_ids: Generated<Json>;
  self_approved: Generated<number>;
  site_id: Buffer | null;
  status: Generated<string>;
  subject_id: Buffer;
  subject_summary: string;
  subject_type: string;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
  zone_id: Buffer | null;
}

export interface ApprovalsControlPolicies {
  approver_permission: string | null;
  approver_scope: string | null;
  code: string;
  condition: Generated<Json>;
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  operation_type: string;
  requires_approval: Generated<number>;
  requires_comment: Generated<number>;
  requires_photo: Generated<number>;
  status: Generated<string>;
  valid_from: Date;
  valid_to: Date | null;
  version: Generated<number>;
}

export interface AttachmentsAttachments {
  backdated_reason: string | null;
  captured_at: Date;
  captured_lat: Decimal | null;
  captured_lng: Decimal | null;
  captured_offline: Generated<number>;
  client_created_at: Date | null;
  clock_suspect: Generated<number>;
  command_id: Buffer | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  created_device_id: Buffer | null;
  id: Buffer;
  kind: string;
  mime_type: string;
  occurred_at: Date;
  owner_id: Buffer;
  owner_type: string;
  received_at: Date | null;
  sha256: string;
  size_bytes: number;
  storage_key: string | null;
  superseded_by_id: Buffer | null;
  upload_status: Generated<string>;
  uploaded_bytes: Generated<number>;
}

export interface AuditAuditLog {
  action: string;
  actor_roles: Json;
  actor_user_id: Buffer;
  after: Json | null;
  approval_request_id: Buffer | null;
  before: Json | null;
  captured_offline: Generated<number>;
  clock_skew_ms: number | null;
  command_id: Buffer | null;
  correlation_id: Buffer | null;
  device_id: Buffer | null;
  entity_id: Buffer | null;
  entity_type: string;
  error_code: string | null;
  id: Buffer;
  ip: string | null;
  occurred_at: Date;
  prev_hash: string;
  reason: string | null;
  recorded_at: Generated<Date>;
  result: string;
  row_hash: string;
  seq: Generated<number>;
  site_id: Buffer | null;
  sync_delay_ms: number | null;
  user_agent: string | null;
}

export interface CatalogCustomerCategories {
  code: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  is_active: Generated<number>;
  name: string;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface CatalogProductCategories {
  code: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  is_active: Generated<number>;
  name: string;
  parent_id: Buffer | null;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface CatalogProducts {
  base_unit_code: string;
  category_id: Buffer;
  code: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  expiry_tracking: Generated<number>;
  id: Buffer;
  is_consumable: Generated<number>;
  is_producible: Generated<number>;
  is_purchasable: Generated<number>;
  is_sellable: Generated<number>;
  lot_tracking: Generated<string>;
  name: string;
  pricing_mode: Generated<string>;
  sellable_since: Date | null;
  species: string | null;
  status: Generated<string>;
  stock_family: string;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface CatalogProductStandardCosts {
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  product_id: Buffer;
  reason: string | null;
  unit_cost_xaf: number;
  valid_from: Date;
}

export interface CatalogProductUnits {
  created_at: Generated<Date>;
  created_by: Buffer;
  factor_to_base: Decimal;
  id: Buffer;
  is_active: Generated<number>;
  is_count_unit: Generated<number>;
  is_purchase_unit: Generated<number>;
  is_sales_unit: Generated<number>;
  product_id: Buffer;
  unit_code: string;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface CatalogReasonCodes {
  category: string;
  code: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  is_active: Generated<number>;
  label: string;
  loss_category: string | null;
  requires_comment: Generated<number>;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface CatalogSalesChannels {
  code: string;
  is_active: Generated<number>;
  name: string;
}

export interface CatalogUnits {
  code: string;
  is_active: Generated<number>;
  is_count: number;
  name: string;
}

export interface IdentityAuthSessions {
  created_at: Generated<Date>;
  device_id: Buffer;
  expires_at: Date;
  id: Buffer;
  ip_first: string | null;
  ip_last: string | null;
  last_used_at: Generated<Date>;
  offline_grant_until: Date;
  refresh_token_hash: string;
  revoked_at: Date | null;
  revoked_reason: string | null;
  token_family_id: Buffer;
  user_id: Buffer;
}

export interface IdentityDevices {
  app_version: string | null;
  approved_by: Buffer | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  designated_site_id: Buffer | null;
  enrolled_by_user_id: Buffer;
  id: Buffer;
  is_shared: Generated<number>;
  label: string | null;
  last_seen_at: Date | null;
  platform: string | null;
  short_code: string;
  status: Generated<string>;
  status_changed_at: Generated<Date>;
  status_reason: string | null;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface IdentityLoginAttempts {
  blocked_until: Date | null;
  failed_count: Generated<number>;
  scope_type: string;
  scope_value: string;
  updated_at: Generated<Date>;
}

export interface IdentityPermissions {
  code: string;
  deprecated_at: Date | null;
  description: string;
  is_approval: Generated<number>;
  is_sensitive: Generated<number>;
  module: string;
  supported_scopes: Json;
}

export interface IdentityRolePermissions {
  granted_at: Generated<Date>;
  granted_by: Buffer;
  limits: Json | null;
  max_scope: string;
  permission_code: string;
  role_id: Buffer;
}

export interface IdentityRoles {
  allowed_scope_types: Generated<Json>;
  code: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  description: string | null;
  id: Buffer;
  is_active: Generated<number>;
  is_system: Generated<number>;
  name: string;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface IdentityUserRoleAssignments {
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  revoke_reason: string | null;
  revoked_at: Date | null;
  revoked_by: Buffer | null;
  role_id: Buffer;
  scope_site_id: Buffer | null;
  scope_team_id: Buffer | null;
  scope_type: Generated<string>;
  scope_zone_id: Buffer | null;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  user_id: Buffer;
  valid_from: Generated<Date>;
  valid_to: Date | null;
  version: Generated<number>;
}

export interface IdentityUsers {
  active_phone: string | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  email: string | null;
  full_name: string;
  id: Buffer;
  is_system: Generated<number>;
  last_login_at: Date | null;
  locale: Generated<string>;
  must_change_password: Generated<number>;
  password_hash: string;
  phone: string;
  primary_device_id: Buffer | null;
  status: Generated<string>;
  status_changed_at: Date | null;
  status_reason: string | null;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface InventoryConsumptions {
  backdated_reason: string | null;
  cancel_approval_request_id: Buffer | null;
  cancel_comment: string | null;
  cancel_reason_code_id: Buffer | null;
  cancelled_at: Date | null;
  cancelled_by: Buffer | null;
  captured_offline: Generated<number>;
  client_created_at: Date | null;
  clock_suspect: Generated<number>;
  command_id: Buffer | null;
  cost_object_id: Buffer;
  cost_object_type: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  created_device_id: Buffer | null;
  id: Buffer;
  location_id: Buffer;
  lot_id: Buffer | null;
  occurred_at: Date;
  product_id: Buffer;
  quantity: Decimal;
  quantity_base: Decimal;
  received_at_server: Date | null;
  recorded_by: Buffer;
  status: Generated<string>;
  unit_code: string;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  value_xaf: number;
  version: Generated<number>;
}

export interface InventoryCostEntries {
  amount_xaf: number;
  comment: string | null;
  cost_object_id: Buffer;
  cost_object_type: string;
  cost_type: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  direction: Generated<string>;
  id: Buffer;
  occurred_at: Date;
  reverses_entry_id: Buffer | null;
  source_id: Buffer;
  source_type: string;
}

export interface InventoryInventoryCountLines {
  command_id: Buffer | null;
  comment: string | null;
  count_id: Buffer;
  counted_at: Date;
  counted_qty_base: Decimal;
  declared_unit_cost_xaf: number | null;
  id: Buffer;
  lot_id: Buffer | null;
  lot_key: Buffer | null;
  product_id: Buffer;
  reconciled_adjustment_qty_base: Generated<Decimal>;
  theoretical_qty_base: Decimal | null;
  unit_cost_xaf: number | null;
  variance_qty_base: Decimal | null;
  variance_reason_code_id: Buffer | null;
}

export interface InventoryInventoryCounts {
  abs_variance_value_xaf: number | null;
  approval_request_id: Buffer | null;
  backdated_reason: string | null;
  captured_offline: Generated<number>;
  client_created_at: Date | null;
  clock_suspect: Generated<number>;
  command_id: Buffer | null;
  count_type: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  created_device_id: Buffer | null;
  doc_number: string;
  id: Buffer;
  in_progress_key: Buffer | null;
  local_ref: string | null;
  location_id: Buffer;
  net_variance_after_reconciliation_xaf: number | null;
  occurred_at: Date;
  opened_by: Buffer | null;
  opening_posted_key: Buffer | null;
  posted_at: Date | null;
  received_at_server: Date | null;
  site_id: Buffer;
  status: string;
  submitted_at: Date | null;
  submitted_by: Buffer | null;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  variance_value_xaf: number | null;
  version: Generated<number>;
}

export interface InventoryLossDeclarations {
  approval_request_id: Buffer | null;
  backdated_reason: string | null;
  business_date: Date | null;
  cancel_approval_request_id: Buffer | null;
  cancel_comment: string | null;
  cancel_reason_code_id: Buffer | null;
  cancelled_at: Date | null;
  cancelled_by: Buffer | null;
  captured_offline: Generated<number>;
  category: string;
  client_created_at: Date | null;
  clock_suspect: Generated<number>;
  command_id: Buffer | null;
  comment: string | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  created_device_id: Buffer | null;
  declared_by: Buffer;
  doc_number: string;
  id: Buffer;
  local_ref: string | null;
  location_id: Buffer;
  lot_id: Buffer | null;
  occurred_at: Date;
  policy_id: Buffer | null;
  policy_version: number | null;
  product_id: Buffer;
  production_lot_id: Buffer | null;
  quantity: Decimal;
  quantity_base: Decimal;
  reason_code_id: Buffer | null;
  received_at_server: Date | null;
  requires_approval: Generated<number>;
  requires_photo: Generated<number>;
  responsibility_user_id: Buffer | null;
  site_id: Buffer;
  status: string;
  unit_code: string;
  unit_cost_xaf: number;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  value_xaf: number;
  version: Generated<number>;
}

export interface InventoryProductValuations {
  avg_unit_cost_xaf: Generated<Decimal>;
  last_entry_move_id: Buffer | null;
  product_id: Buffer;
  qty_basis: Generated<Decimal>;
  updated_at: Generated<Date>;
}

export interface InventoryStockAllocationEntries {
  allocation_id: Buffer;
  command_id: Buffer | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  entry_type: string;
  id: Buffer;
  occurred_at: Date;
  quantity: Decimal;
  stock_move_id: Buffer | null;
}

export interface InventoryStockAllocations {
  active_device_quota_key: string | null;
  allocation_type: string;
  close_cause: string | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  granted_by: Buffer;
  holder_device_id: Buffer | null;
  holder_user_id: Buffer | null;
  id: Buffer;
  location_id: Buffer;
  lot_id: Buffer | null;
  product_id: Buffer;
  quantity_granted: Decimal;
  quantity_remaining: Decimal;
  revocation_pending: Generated<number>;
  sales_order_line_id: Buffer | null;
  status: Generated<string>;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  valid_until: Date | null;
  version: Generated<number>;
}

export interface InventoryStockBalances {
  last_move_at: Date | null;
  location_id: Buffer;
  lot_key: Buffer;
  product_id: Buffer;
  qty_allocated: Generated<Decimal>;
  qty_on_hand: Generated<Decimal>;
  qty_reserved: Generated<Decimal>;
  row_version: Generated<number>;
  updated_at: Generated<Date>;
  value_xaf: Generated<number>;
}

export interface InventoryStockLots {
  created_at: Generated<Date>;
  created_by: Buffer;
  expiry_date: Date | null;
  fifo_rank_at: Date;
  id: Buffer;
  lot_code: string;
  origin_id: Buffer | null;
  origin_type: string;
  product_id: Buffer | null;
  status: Generated<string>;
  supplier_id: Buffer | null;
  supplier_lot_ref: string | null;
}

export interface InventoryStockMoves {
  allocation_id: Buffer | null;
  business_date: Date | null;
  captured_offline: Generated<number>;
  command_id: Buffer | null;
  cost_object_id: Buffer | null;
  cost_object_type: string | null;
  created_by: Buffer;
  created_device_id: Buffer | null;
  from_location_id: Buffer;
  id: Buffer;
  is_reversal: Generated<number>;
  lot_id: Buffer | null;
  move_type: string;
  occurred_at: Date;
  product_id: Buffer;
  quantity: Decimal;
  reason_code_id: Buffer | null;
  recorded_at: Generated<Date>;
  reverses_move_id: Buffer | null;
  source_doc_id: Buffer;
  source_doc_type: string;
  source_line_id: Buffer | null;
  to_location_id: Buffer;
  unit_cost_xaf: number;
  value_xaf: number;
}

export interface InventoryStockThresholds {
  active_key: string | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  is_active: Generated<number>;
  location_id: Buffer;
  min_qty_base: Decimal;
  product_id: Buffer;
  target_qty_base: Decimal;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface InventoryStockTransferLines {
  discrepancy_qty_base: Decimal | null;
  discrepancy_reason_code_id: Buffer | null;
  dispatched_qty_base: Decimal | null;
  id: Buffer;
  lot_id: Buffer | null;
  product_id: Buffer;
  received_qty_base: Decimal | null;
  requested_qty_base: Decimal | null;
  returned_qty_base: Generated<Decimal>;
  transfer_id: Buffer;
  unit_code: string;
}

export interface InventoryStockTransfers {
  approval_request_id: Buffer | null;
  backdated_reason: string | null;
  captured_offline: Generated<number>;
  carrier_name: string | null;
  carrier_user_id: Buffer | null;
  client_created_at: Date | null;
  clock_suspect: Generated<number>;
  command_id: Buffer | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  created_device_id: Buffer | null;
  dispatched_at: Date | null;
  dispatched_by: Buffer | null;
  doc_number: string;
  from_location_id: Buffer;
  id: Buffer;
  local_ref: string | null;
  matched_transfer_id: Buffer | null;
  notes: string | null;
  occurred_at: Date;
  received_at: Date | null;
  received_at_server: Date | null;
  received_by: Buffer | null;
  requested_at: Date | null;
  requested_by: Buffer | null;
  sales_order_id: Buffer | null;
  site_id: Buffer;
  status: string;
  to_location_id: Buffer;
  transfer_kind: Generated<string>;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface OrganizationLocations {
  active_mobile_custodian: Buffer | null;
  active_virtual_type: string | null;
  capacity: number | null;
  code: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  custodian_user_id: Buffer | null;
  custody_mode: string | null;
  designated_device_id: Buffer | null;
  id: Buffer;
  is_virtual: number | null;
  location_type: string;
  name: string;
  parent_location_id: Buffer | null;
  site_id: Buffer | null;
  status: Generated<string>;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface OrganizationPointsOfSale {
  created_at: Generated<Date>;
  created_by: Buffer;
  custody_mode: Generated<string>;
  designated_device_id: Buffer | null;
  opening_hours: string | null;
  replenishment_source_location_id: Buffer | null;
  sales_location_id: Buffer;
  site_id: Buffer;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface OrganizationSites {
  address: string | null;
  closed_on: Date | null;
  code: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  lat: Decimal | null;
  lng: Decimal | null;
  name: string;
  opened_on: Date | null;
  site_type: string;
  status: Generated<string>;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
  zone_id: Buffer;
}

export interface OrganizationSystemSettings {
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  is_client_visible: Generated<number>;
  key: string;
  reason: string | null;
  scope_id: Buffer | null;
  scope_type: Generated<string>;
  valid_from: Generated<Date>;
  value: Json;
}

export interface OrganizationTeamMemberships {
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  team_id: Buffer;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  user_id: Buffer;
  valid_from: Date;
  valid_to: Date | null;
  version: Generated<number>;
}

export interface OrganizationTeams {
  code: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  is_active: Generated<number>;
  manager_user_id: Buffer;
  name: string;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface OrganizationZoneAncestors {
  ancestor_id: Buffer;
  depth: number;
  zone_id: Buffer;
}

export interface OrganizationZones {
  code: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  depth: number;
  geofence_lat: Decimal | null;
  geofence_lng: Decimal | null;
  geofence_radius_m: Decimal | null;
  id: Buffer;
  is_active: Generated<number>;
  level: string;
  max_gps_accuracy_m: Generated<Decimal | null>;
  name: string;
  parent_id: Buffer | null;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface PlatformDocumentSequences {
  doc_type: string;
  next_value: Generated<number>;
  site_id: Buffer;
  year: number;
}

export interface PlatformDomainEvents {
  aggregate_id: Buffer;
  aggregate_type: string;
  causation_id: Buffer | null;
  command_id: Buffer | null;
  correlation_id: Buffer | null;
  event_id: Buffer;
  event_type: string;
  event_version: Generated<number>;
  occurred_at: Date;
  payload: Json;
  producer_module: string;
  recorded_at: Generated<Date>;
  seq: Generated<number>;
}

export interface PlatformEventConsumerMarks {
  consumer_name: string;
  event_id: Buffer;
  processed_at: Generated<Date>;
}

export interface PlatformEventConsumerOffsets {
  consumer_name: string;
  last_error: string | null;
  last_seq: Generated<number>;
  updated_at: Generated<Date>;
}

export interface PlatformJobs {
  attempts: Generated<number>;
  completed_at: Date | null;
  created_at: Generated<Date>;
  id: Buffer;
  job_type: string;
  last_error: string | null;
  max_attempts: Generated<number>;
  payload: Json;
  run_at: Date;
  status: Generated<string>;
}

export interface PricingCommercialCampaigns {
  code: string;
  created_at: Generated<Date>;
  created_by: Buffer;
  id: Buffer;
  name: string;
  status: Generated<string>;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  valid_from: Date;
  valid_to: Date;
  version: Generated<number>;
}

export interface PricingPriceRules {
  approved_at: Date | null;
  approved_by: Buffer | null;
  channel_code: string | null;
  code: string;
  commercial_campaign_id: Buffer | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  customer_category_id: Buffer | null;
  id: Buffer;
  min_quantity: Decimal | null;
  notes: string | null;
  pricing_unit_code: string;
  priority: Generated<number>;
  product_id: Buffer;
  site_id: Buffer | null;
  specificity: Generated<number>;
  status: Generated<string>;
  supersedes_rule_id: Buffer | null;
  unit_price_xaf: number;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  valid_from: Date;
  valid_to: Date | null;
  version: Generated<number>;
  zone_id: Buffer | null;
}

export interface ProcurementSuppliers {
  address: string | null;
  code: string;
  contact_name: string | null;
  created_at: Generated<Date>;
  created_by: Buffer;
  email: string | null;
  id: Buffer;
  name: string;
  notes: string | null;
  payment_terms_days: number | null;
  phone: string | null;
  status: Generated<string>;
  supplied_categories: Json;
  tax_id: string | null;
  updated_at: Generated<Date>;
  updated_by: Buffer | null;
  version: Generated<number>;
}

export interface SchemaMigrations {
  version: string;
}

export interface SyncChangeFeed {
  change_type: string;
  dataset: string;
  entity_id: Buffer;
  entity_type: string;
  recorded_at: Generated<Date>;
  row_version: number;
  scope_id: Buffer | null;
  scope_type: string;
  seq: Generated<number>;
}

export interface SyncCommandInbox {
  aggregate_id: Buffer | null;
  aggregate_type: string | null;
  applied_at: Date | null;
  attempts: Generated<number>;
  base_version: number | null;
  batch_id: Buffer | null;
  captured_offline: Generated<number>;
  client_created_at: Date | null;
  clock_skew_ms: number | null;
  command_id: Buffer;
  command_type: string;
  command_version: Generated<number>;
  depends_on: Generated<Json>;
  device_id: Buffer | null;
  device_sent_at: Date | null;
  device_seq: number | null;
  error_code: string | null;
  error_message: string | null;
  occurred_at: Date;
  payload: Json;
  payload_hash: string;
  received_at: Generated<Date>;
  result: Json | null;
  status: Generated<string>;
  transport: string;
  user_id: Buffer;
}

export interface SyncDeviceSyncState {
  app_version: string | null;
  bootstrapped_at: Date | null;
  cursor_seq: Generated<number>;
  dataset: string;
  device_id: Buffer;
  known_gaps: Json | null;
  last_clock_skew_ms: number | null;
  last_device_seq: number | null;
  last_pull_at: Date | null;
  last_push_at: Date | null;
  needs_rebootstrap: Generated<number>;
  pending_reported: number | null;
}

export interface SyncSyncConflicts {
  applied: number;
  command_id: Buffer | null;
  conflict_type: string;
  created_at: Generated<Date>;
  details: Json;
  entity_id: Buffer;
  entity_type: string;
  id: Buffer;
  owner_role: string;
  resolution: string | null;
  resolution_comment: string | null;
  resolution_refs: Generated<Json>;
  resolved_at: Date | null;
  resolved_by: Buffer | null;
  site_id: Buffer | null;
  status: Generated<string>;
}

export interface DB {
  approvals_approval_requests: ApprovalsApprovalRequests;
  approvals_control_policies: ApprovalsControlPolicies;
  attachments_attachments: AttachmentsAttachments;
  audit_audit_log: AuditAuditLog;
  catalog_customer_categories: CatalogCustomerCategories;
  catalog_product_categories: CatalogProductCategories;
  catalog_product_standard_costs: CatalogProductStandardCosts;
  catalog_product_units: CatalogProductUnits;
  catalog_products: CatalogProducts;
  catalog_reason_codes: CatalogReasonCodes;
  catalog_sales_channels: CatalogSalesChannels;
  catalog_units: CatalogUnits;
  identity_auth_sessions: IdentityAuthSessions;
  identity_devices: IdentityDevices;
  identity_login_attempts: IdentityLoginAttempts;
  identity_permissions: IdentityPermissions;
  identity_role_permissions: IdentityRolePermissions;
  identity_roles: IdentityRoles;
  identity_user_role_assignments: IdentityUserRoleAssignments;
  identity_users: IdentityUsers;
  inventory_consumptions: InventoryConsumptions;
  inventory_cost_entries: InventoryCostEntries;
  inventory_inventory_count_lines: InventoryInventoryCountLines;
  inventory_inventory_counts: InventoryInventoryCounts;
  inventory_loss_declarations: InventoryLossDeclarations;
  inventory_product_valuations: InventoryProductValuations;
  inventory_stock_allocation_entries: InventoryStockAllocationEntries;
  inventory_stock_allocations: InventoryStockAllocations;
  inventory_stock_balances: InventoryStockBalances;
  inventory_stock_lots: InventoryStockLots;
  inventory_stock_moves: InventoryStockMoves;
  inventory_stock_thresholds: InventoryStockThresholds;
  inventory_stock_transfer_lines: InventoryStockTransferLines;
  inventory_stock_transfers: InventoryStockTransfers;
  organization_locations: OrganizationLocations;
  organization_points_of_sale: OrganizationPointsOfSale;
  organization_sites: OrganizationSites;
  organization_system_settings: OrganizationSystemSettings;
  organization_team_memberships: OrganizationTeamMemberships;
  organization_teams: OrganizationTeams;
  organization_zone_ancestors: OrganizationZoneAncestors;
  organization_zones: OrganizationZones;
  platform_document_sequences: PlatformDocumentSequences;
  platform_domain_events: PlatformDomainEvents;
  platform_event_consumer_marks: PlatformEventConsumerMarks;
  platform_event_consumer_offsets: PlatformEventConsumerOffsets;
  platform_jobs: PlatformJobs;
  pricing_commercial_campaigns: PricingCommercialCampaigns;
  pricing_price_rules: PricingPriceRules;
  procurement_suppliers: ProcurementSuppliers;
  schema_migrations: SchemaMigrations;
  sync_change_feed: SyncChangeFeed;
  sync_command_inbox: SyncCommandInbox;
  sync_device_sync_state: SyncDeviceSyncState;
  sync_sync_conflicts: SyncSyncConflicts;
}
